import '../models/user_model.dart';
import '../models/booking_model.dart';
import '../models/review_model.dart';
import '../models/chat_model.dart';

class MockData {
  static final List<UserModel> friends = [
    UserModel(
      id: '1',
      name: 'Elif Yılmaz',
      email: 'elif@yeyey.com',
      photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
      bio: 'Hayatı seviyorum! Kahve içmeyi, seyahat etmeyi ve yeni insanlarla tanışmayı çok seviyorum. 🌟',
      city: 'İstanbul',
      age: 25,
      gender: 'Kadın',
      isFriendForRent: true,
      hourlyRate: 150,
      rating: 4.8,
      totalReviews: 124,
      totalBookings: 89,
      categories: ['kahve', 'seyahat', 'sohbet', 'alisveris'],
      interests: ['Fotoğrafçılık', 'Yoga', 'Kitap', 'Kahve'],
      languages: ['Türkçe', 'İngilizce'],
      isVerified: true,
      isOnline: true,
      createdAt: DateTime(2025, 6, 15),
    ),
    UserModel(
      id: '2',
      name: 'Ahmet Kaya',
      email: 'ahmet@yeyey.com',
      photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
      bio: 'Spor tutkunu, doğa aşığı! Futbol, basketbol, yüzme... Her türlü spor aktivitesi için buradayım! 💪',
      city: 'İstanbul',
      age: 28,
      gender: 'Erkek',
      isFriendForRent: true,
      hourlyRate: 120,
      rating: 4.6,
      totalReviews: 87,
      totalBookings: 65,
      categories: ['spor', 'egzersiz', 'dogayuruyusu'],
      interests: ['Futbol', 'Basketbol', 'Koşu', 'Doğa'],
      languages: ['Türkçe', 'İngilizce', 'Almanca'],
      isVerified: true,
      isOnline: false,
      createdAt: DateTime(2025, 5, 20),
    ),
    UserModel(
      id: '3',
      name: 'Zeynep Demir',
      email: 'zeynep@yeyey.com',
      photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
      bio: 'Film ve dizi gurusu! 🎬 Sinemaya gitmek veya evde film maratonu yapmak ister misin?',
      city: 'Ankara',
      age: 23,
      gender: 'Kadın',
      isFriendForRent: true,
      hourlyRate: 100,
      rating: 4.9,
      totalReviews: 156,
      totalBookings: 112,
      categories: ['sinema', 'sohbet', 'yemek', 'kahve'],
      interests: ['Film', 'Dizi', 'Anime', 'Müzik'],
      languages: ['Türkçe', 'İngilizce', 'Japonca'],
      isVerified: true,
      isOnline: true,
      createdAt: DateTime(2025, 3, 10),
    ),
    UserModel(
      id: '4',
      name: 'Can Özkan',
      email: 'can@yeyey.com',
      photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
      bio: 'Gamer arkadaş arıyorsan doğru adrestesin! PC, PS5, Nintendo Switch... Hepsinde varım! 🎮',
      city: 'İzmir',
      age: 26,
      gender: 'Erkek',
      isFriendForRent: true,
      hourlyRate: 90,
      rating: 4.7,
      totalReviews: 203,
      totalBookings: 178,
      categories: ['oyun', 'sohbet', 'yemek'],
      interests: ['Gaming', 'Teknoloji', 'Manga', 'Pizza'],
      languages: ['Türkçe', 'İngilizce'],
      isVerified: true,
      isOnline: true,
      createdAt: DateTime(2025, 4, 5),
    ),
    UserModel(
      id: '5',
      name: 'Selin Arslan',
      email: 'selin@yeyey.com',
      photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
      bio: 'Müzik ruhumu besliyor! 🎵 Konserlere gitmek, müzik dinlemek, gitar çalmak... Hadi birlikte yapalım!',
      city: 'İstanbul',
      age: 24,
      gender: 'Kadın',
      isFriendForRent: true,
      hourlyRate: 130,
      rating: 4.5,
      totalReviews: 67,
      totalBookings: 45,
      categories: ['muzik', 'kahve', 'sohbet', 'seyahat'],
      interests: ['Gitar', 'Konser', 'Şarkı Söyleme', 'Dans'],
      languages: ['Türkçe', 'İngilizce', 'İspanyolca'],
      isVerified: false,
      isOnline: false,
      createdAt: DateTime(2025, 7, 22),
    ),
    UserModel(
      id: '6',
      name: 'Burak Çelik',
      email: 'burak@yeyey.com',
      photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
      bio: 'Gurme bir arkadaş mı arıyorsun? İstanbul\'un en iyi restoranlarını keşfedelim! 🍕',
      city: 'İstanbul',
      age: 30,
      gender: 'Erkek',
      isFriendForRent: true,
      hourlyRate: 180,
      rating: 4.9,
      totalReviews: 312,
      totalBookings: 245,
      categories: ['yemek', 'kahve', 'sohbet', 'alisveris'],
      interests: ['Yemek Yapma', 'Restoran', 'Şarap', 'Seyahat'],
      languages: ['Türkçe', 'İngilizce', 'Fransızca', 'İtalyanca'],
      isVerified: true,
      isOnline: true,
      createdAt: DateTime(2025, 1, 8),
    ),
  ];

  static final List<ReviewModel> reviews = [
    ReviewModel(
      id: 'r1',
      bookingId: 'b1',
      reviewerId: 'u1',
      reviewerName: 'Merve K.',
      reviewerPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100',
      friendId: '1',
      rating: 5.0,
      comment: 'Elif harika bir arkadaş! Çok eğlendik. Kesinlikle tekrar buluşmak isterim.',
      createdAt: DateTime(2026, 2, 10),
    ),
    ReviewModel(
      id: 'r2',
      bookingId: 'b2',
      reviewerId: 'u2',
      reviewerName: 'Oğuz T.',
      reviewerPhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100',
      friendId: '1',
      rating: 4.5,
      comment: 'Kahve sohbetimiz çok güzeldi. Elif çok sıcak ve samimi birisi.',
      createdAt: DateTime(2026, 2, 5),
    ),
    ReviewModel(
      id: 'r3',
      bookingId: 'b3',
      reviewerId: 'u3',
      reviewerName: 'Ayşe D.',
      reviewerPhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100',
      friendId: '2',
      rating: 4.8,
      comment: 'Ahmet ile spor yapmak çok motive edici! Harika bir antrenman partneri.',
      createdAt: DateTime(2026, 1, 28),
    ),
  ];

  static final List<BookingModel> bookings = [
    BookingModel(
      id: 'b1',
      clientId: 'currentUser',
      friendId: '1',
      clientName: 'Ben',
      friendName: 'Elif Yılmaz',
      date: DateTime(2026, 2, 20),
      startTime: '14:00',
      endTime: '16:00',
      hours: 2,
      totalPrice: 300,
      category: 'kahve',
      note: 'Kadıköy\'de buluşalım',
      status: BookingStatus.confirmed,
      createdAt: DateTime(2026, 2, 18),
    ),
    BookingModel(
      id: 'b2',
      clientId: 'currentUser',
      friendId: '4',
      clientName: 'Ben',
      friendName: 'Can Özkan',
      date: DateTime(2026, 2, 22),
      startTime: '20:00',
      endTime: '23:00',
      hours: 3,
      totalPrice: 270,
      category: 'oyun',
      note: 'Online oyun oynayalım',
      status: BookingStatus.pending,
      createdAt: DateTime(2026, 2, 19),
    ),
  ];

  static final List<ChatRoom> chatRooms = [
    ChatRoom(
      id: 'chat1',
      otherUserId: '1',
      otherUserName: 'Elif Yılmaz',
      otherUserPhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
      lastMessage: 'Harika, yarın görüşürüz! 😊',
      lastMessageTime: DateTime(2026, 2, 19, 14, 30),
      unreadCount: 2,
      isOnline: true,
    ),
    ChatRoom(
      id: 'chat2',
      otherUserId: '4',
      otherUserName: 'Can Özkan',
      otherUserPhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
      lastMessage: 'Hangi oyunu oynayalım?',
      lastMessageTime: DateTime(2026, 2, 19, 12, 15),
      unreadCount: 0,
      isOnline: true,
    ),
    ChatRoom(
      id: 'chat3',
      otherUserId: '6',
      otherUserName: 'Burak Çelik',
      otherUserPhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
      lastMessage: 'O restoran çok iyi, kesinlikle gidelim!',
      lastMessageTime: DateTime(2026, 2, 18, 20, 45),
      unreadCount: 1,
      isOnline: false,
    ),
  ];
}
